### ISSUE TITLE
 A question

### ISSUE THREAD

**Issue by lduhejian** [nextapps-be/unique-codes#2]
### Description:
I've read your post about the source(https://gdebrauwer.dev/blog/generating-unique-voucher-codes/). But i get different result, I don't know why?
```
encodeNumber(1) == 213456
encodeNumber(665281) == 24ECAD
encodeNumber(1)  != encodeNumber(665281)
```
Can you give me the answer, thank you!
<img width="967" alt="截屏2021-01-28 下午1 53 50" src="https://user-images.githubusercontent.com/8924298/106096696-0485ac00-6171-11eb-87a2-c0f8f362ba81.png">

**Comment by gdebrauwer** [comment]
You get a different result because that sentence is incorrect I just discovered 😅 This also means that the package contains a bug. This bug is caused by the prevention of duplicate characters in the encoded result. So certain input numbers can currently have the same output code because of this.

Thanks for noticing and notifying us! 🙏 We will fix this as soon as possible

**Comment by gdebrauwer** [comment]
A PR has been created #3

**Comment by lduhejian** [comment]
**encodeNumber(1)  != encodeNumber(665281)** also !

<img width="438" alt="截屏2021-01-29 下午12 11 47" src="https://user-images.githubusercontent.com/8924298/106230856-63a7f700-622b-11eb-819b-4b81d338a143.png">

**Comment by lduhejian** [comment]
```
    protected function getMaximumUniqueCodes()
    {
        $maxCombinations = 1;

        for ($i = 0; $i < $this->length; $i++) {
            $maxCombinations = $maxCombinations * (strlen($this->characters) - $i);
        }

        return $maxCombinations;
    }
```
This function also needs to be modified as follow.
```
    protected function getMaximumUniqueCodes()
    {
        return pow(strlen($this->characters),$this->length);
    }
```
